name: Build & Export

on:
  push:
    branches: [ "master" ] 
  workflow_dispatch: {}

jobs:
  export:
    runs-on: [self-hosted]
    timeout-minutes: 30

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Enable exporter define
        shell: bash
        run: |
          echo "#define MAP_EXPORTER" > tools/exporter/_defines.dm

      - name: Build DM + TGUI
        shell: cmd
        run: |
          tools\build\build.bat dm
          
      - name: Run DreamDaemon to generate exports
        shell: cmd
        run: |
          REM Adjust paths/names to the .dmb produced by your build
          set DMB=aurorastation.m.dmb
          if not exist %DMB% (
            echo DMB not found!
            dir /b
            exit /b 1
          )
          start "" /B DreamDaemon.exe %DMB% -invisible -trusted -close
          timeout /t 20 >NUL

      - name: List exports
        shell: cmd
        run: |
          if exist data\exports (
            dir data\exports
          ) else (
            echo No exports found in data\exports
            exit /b 1
          )

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aurora-exports-${{ github.sha }}
          path: |
            data/exports/**
          if-no-files-found: error
