name: Sync Fork from Upstream

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 min; adjust as you like
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Aurorastation/Aurora.3.git
          git fetch upstream

      - name: Fast-forward master from upstream/master
        run: |
          git checkout master
          # Only update if upstream changed:
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse upstream/master)" ]; then
            git merge --ff-only upstream/master
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:master
            echo "PUSHED=true" >> $GITHUB_ENV
          else
            echo "PUSHED=false" >> $GITHUB_ENV
          fi

      - name: Summary
        run: echo "Pushed: $PUSHED"
